// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.Domain.Entities;

namespace NextGen.Mantenimiento.Entities;


[Table("Personal")]
public class Personal: Entity<int>
{
    //public int Id { get; set; }

    public int DepartamentoId { get; set; }

    public int CategoriaId { get; set; }

    public string Nombre { get; set; }

    public string Apellidos { get; set; }

    public DateTime FechaNacimiento { get; set; }

    public string Dni { get; set; }

    public string Telefono { get; set; }

    public string Direccion { get; set; }

    public string CorreoElectronico { get; set; }

    public DateTime FechaAlta { get; set; }

    public DateTime? FechaBaja { get; set; }

    public string NombreCategoria { get; set; }

    public string NombreDepartamento { get; set; }
}